#!/bin/bash

conda update --all -y

# Enable the proxy extension in notebook and lab
jupyter serverextension enable --sys-prefix jupyter_server_proxy
jupyter labextension install @jupyterlab/server-proxy
jupyter lab build

code-server --install-extension ms-python.python

# Install the VS code proxy
pip install -e.
